version: '2'

services:
  wp:
    image: techblog:latest
    ports:
      - "80:80"
    depends_on:
      - db_for_wp
    environment:
      - WORDPRESS_DB_HOST=db_for_wp:3306
      - WORDPRESS_DB_PASSWORD=example
    restart: always

  db_for_wp:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=example
    restart: always
