version: '2'

services:
  wp:
    image: techblog:latest
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=ec2-13-124-31-153.ap-northeast-2.compute.amazonaws.com:3306
      - WORDPRESS_DB_PASSWORD=example
    restart: always